name: tfsec

on: pull_request

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
